# Statically link the MSVC C runtime so the Windows build has no
# dependency on the VC++ Redistributable being installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
