// Declarative menu definitions rendered by MenuBar. Every leaf is a
// registered command id (single source of truth with the palette).

export type MenuEntry =
  | { type: "command"; id: string; label?: string }
  | { type: "separator" }
  | { type: "submenu"; label: string; items: MenuEntry[] }
  | { type: "dynamic"; key: "recent-files" | "recent-workspaces" };

export type MenuDefinition = {
  label: string;
  items: MenuEntry[];
};

const sep: MenuEntry = { type: "separator" };
const c = (id: string, label?: string): MenuEntry => ({
  type: "command",
  id,
  label,
});

export const MENUS: MenuDefinition[] = [
  {
    label: "File",
    items: [
      c("file.new"),
      c("file.newFromTemplate"),
      c("file.newWindow"),
      sep,
      c("file.open"),
      c("file.openFolder"),
      {
        type: "submenu",
        label: "Open Recent",
        items: [{ type: "dynamic", key: "recent-files" }],
      },
      {
        type: "submenu",
        label: "Recent Workspaces",
        items: [{ type: "dynamic", key: "recent-workspaces" }],
      },
      sep,
      c("file.save"),
      c("file.saveAs"),
      c("file.saveAll"),
      sep,
      c("file.duplicate"),
      c("file.revealInFileManager"),
      sep,
      c("file.close"),
      c("file.closeWorkspace"),
      sep,
      c("file.export", "Export…"),
      c("file.print"),
      sep,
      c("file.preferences"),
      c("file.exit"),
    ],
  },
  {
    label: "Edit",
    items: [
      c("edit.undo"),
      c("edit.redo"),
      sep,
      c("edit.cut"),
      c("edit.copy"),
      c("edit.paste"),
      c("edit.pastePlain"),
      c("edit.selectAll"),
      sep,
      c("edit.find"),
      c("edit.replace"),
      c("edit.findInFiles"),
      sep,
      c("edit.goToLine"),
      c("edit.goToHeading"),
      sep,
      c("edit.toggleComment"),
      c("edit.duplicateLine"),
      c("edit.deleteLine"),
      c("edit.moveLineUp"),
      c("edit.moveLineDown"),
      sep,
      c("edit.sortLines"),
      c("edit.trimWhitespace"),
      c("edit.tabsToSpaces"),
      c("edit.spacesToTabs"),
    ],
  },
  {
    label: "View",
    items: [
      c("view.editorOnly"),
      c("view.split"),
      c("view.previewOnly"),
      c("view.mermaidStudio"),
      sep,
      c("view.toggleSidebar"),
      c("view.toggleRightPanel"),
      c("view.toggleToolbar"),
      c("view.toggleStatusBar"),
      sep,
      c("view.zenMode"),
      c("view.typewriterMode"),
      c("view.toggleWordWrap"),
      c("view.toggleMinimap"),
      sep,
      c("view.zoomIn"),
      c("view.zoomOut"),
      c("view.resetZoom"),
      sep,
      c("view.toggleTheme", "Toggle Dark Mode"),
      {
        type: "submenu",
        label: "Theme",
        items: [
          c("view.themeSystem", "System"),
          c("view.themeLight", "Light"),
          c("view.themeDark", "Dark"),
        ],
      },
    ],
  },
  {
    label: "Insert",
    items: [
      c("insert.h1"),
      c("insert.h2"),
      c("insert.h3"),
      sep,
      c("insert.bold"),
      c("insert.italic"),
      c("insert.strikethrough"),
      c("insert.inlineCode"),
      c("insert.codeBlock"),
      c("insert.blockquote"),
      sep,
      c("insert.orderedList"),
      c("insert.unorderedList"),
      c("insert.taskList"),
      sep,
      c("insert.link"),
      c("insert.image"),
      c("insert.table"),
      c("insert.hr"),
      c("insert.footnote"),
      {
        type: "submenu",
        label: "Callout",
        items: [
          c("insert.calloutNOTE", "Note"),
          c("insert.calloutTIP", "Tip"),
          c("insert.calloutIMPORTANT", "Important"),
          c("insert.calloutWARNING", "Warning"),
          c("insert.calloutCAUTION", "Caution"),
        ],
      },
      sep,
      c("insert.mermaid"),
      c("insert.snippet"),
      sep,
      c("insert.date"),
      c("insert.time"),
      c("insert.frontmatter"),
      c("insert.htmlBlock"),
    ],
  },
  {
    label: "Format",
    items: [
      c("format.document"),
      c("format.selection"),
      sep,
      c("format.normalizeHeadings"),
      c("format.renumberLists"),
      sep,
      c("format.toTable"),
      c("format.toTaskList"),
      sep,
      c("format.wrapParagraph"),
      c("format.unwrapParagraph"),
      sep,
      c("format.cleanMarkdown"),
      c("format.fixTables"),
      c("format.fixMermaidIndentation"),
    ],
  },
  {
    label: "Diagram",
    items: [
      c("diagram.new"),
      sep,
      c("diagram.insert.flowchart"),
      c("diagram.insert.sequence"),
      c("diagram.insert.class"),
      c("diagram.insert.state"),
      c("diagram.insert.er"),
      c("diagram.insert.gantt"),
      c("diagram.insert.pie"),
      c("diagram.insert.mindmap"),
      c("diagram.insert.timeline"),
      sep,
      c("diagram.openStudio"),
    ],
  },
  {
    label: "Export",
    items: [
      c("file.export", "Export Document…"),
      c("file.print", "Print / PDF"),
    ],
  },
  {
    label: "Tools",
    items: [
      c("tools.commandPalette"),
      sep,
      c("tools.linter"),
      c("tools.linkChecker"),
      c("tools.wordCount"),
      sep,
      c("tools.assetManager"),
      c("tools.frontmatterEditor"),
      sep,
      c("tools.snippetManager"),
      c("tools.templateManager"),
      c("tools.backupManager"),
      sep,
      c("tools.devtools"),
    ],
  },
  {
    label: "Window",
    items: [
      c("window.minimize"),
      c("window.maximize"),
      c("window.fullscreen"),
      sep,
      c("file.newWindow"),
      sep,
      c("tab.next"),
      c("tab.previous"),
      c("tab.moveLeft"),
      c("tab.moveRight"),
      sep,
      c("tab.close"),
      c("tab.reopenClosed"),
    ],
  },
  {
    label: "Help",
    items: [
      c("help.docs"),
      c("help.markdownGuide"),
      c("help.mermaidGuide"),
      sep,
      c("help.shortcuts"),
      sep,
      c("help.reportIssue"),
      sep,
      c("help.checkUpdates"),
      c("help.about"),
    ],
  },
];
